**Zadanie 1.** (1 punkt) <br/>
a) Napisz własny klasyfikator K-Nearest Neighbours 
(KNN). Zadanie mo
ż
na wykona
ć
 w Matlabie, 
Pythonie lub innym j
ę
zyku programowania. W zadaniu mo
ż
na u
ż
y
ć
 wcze
ś
niej zaimplementowanej 
funkcji liczenia odległo
ś
ci (na przykład z zadania 0 z listy 3). <br/>
b) Napisany klasyfikator KNN przetestuj na danych I
RIS. Podziel dane losowo na dwie cz
ęś
ci: 100 
wektorów  danych  u
ż
yj  jako  dane  ucz
ą
ce  do  stworzenia  klasyfikatora  i  50  wektorów  danych
  u
ż
yj 
jako  dane  testowe  do  przetestowania  stworzonego  kla
syfikatora.  Powtórz  ten  eksperyment 
kilkukrotnie i porównaj wyniki. <br/>
c) Przeprowad
ź
 te
ż
 podobny test klasyfikatora KNN na danych Optical R
ecognition of Handwritten 
Digits (https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits). <br/>
d) Zrób cross validation klasyfikatora KNN na obu z
estawach danych: podziel dane na 10 cz
ęś
ci, 
kolejno  bierz  jedn
ą
  z  nich,  traktuj  j
ą
  jako  dane  testowe,  a  pozostałe  9  cz
ęś
ci  jako  dane  ucz
ą
ce, 
stwórz  klasyfikator  na  danych  ucz
ą
cych  i  przetestuj  na  danych  testowych,  odnotuj  licz
b
ę
  bł
ę
dów, 
powtórz  obliczenia  dla  kolejnych  cz
ęś
ci  danych,  policz  całkowity  bł
ą
d  klasyfikatora  sumuj
ą
c 
odnotowane liczby bł
ę
dów. 

In [2]:
#1) shuffle
#2) data split
#3) distance calculation
#4) knn predict
#5) accuracy predict

In [32]:
# from sklearn import cross_validation
# #import numpy as np
# def knn_classify(dataset_data, dataset_target, test_size=0, k=3):
#     print(dataset_data)
#     print(dataset_target)
#     x_train, x_test, y_train, y_test = cross_validation.train_test_split(dataset_data, dataset_target, test_size, random_state=1)
#     train = np.array(zip(x_train,y_train))
#     test = np.array(zip(x_test, y_test))
#     nearest = calc_nearest(train, test, k)
    
# def calc_nearest(train, test, k):
#     for i in test:
#         for j in train:
#             dist = np.dot((test-train).T, (test-train))
#             print (dist)

# # coord_difference = (points - centroids[:, np.newaxis, :])
# #     #distances = np.sqrt((coord_difference**2).sum(axis=2)) #can be without sqrt()
# #     distances = (coord_difference**2).sum(axis=2)

In [34]:

#knn_classify(iris.data[:10], iris.target[:10])


**Zadanie 2.** (1 punkt) <br/>
W  pakiecie  SciKit  do  Pythona  dost
ę
pnych  jest  kilka  popularnych  algorytmów  klasyfikacj
i  danych 
przy  u
ż
yciu  drzew  klasyfikacyjnych.  Zapoznaj  si
ę
  z  nimi  wykonuj
ą
c  skrypt  umieszczony  w 
materiałach do wykładu. Do rysowania drzew u
ż
yj programu Graphviz. <br/>
a) Jak
ą
 miar
ę
 ró
ż
norodno
ś
ci stosuje algorytm konstrukcji drzew klasyfikuj
ą
cych u
ż
yty w skrypcie? 
Dla danych Titanic sporz
ą
d
ź
 drzewa klasyfikacyjne stosuj
ą
c indeks Giniego oraz entropi
ę
. <br/>
b)  Podziel  dane  Titanic  na  dane  ucz
ą
ce  i  dane  testowe  (jak  w  zadaniu  1b),  stwórz  drzewa
klasyfikacyjne na danych ucz
ą
cych i przetestuj na danych testowych. <br/>
c)  Spróbuj  ograniczy
ć
  gł
ę
boko
ść
  drzewa.  Zobacz  jak  wpływa  to  na  wyniki  (zarówno  na
  danych 
ucz
ą
cych jak i na danych testowych). <br/>
d) Spróbuj przyci
ąć
 drzewo technik
ą
 omawian
ą
 na wykładzie lub własn
ą
. Zobacz jak wpływa to na 
wyniki (zarówno na danych ucz
ą
cych jak i na danych testowych). <br/>
e) Zrób cross validation wszystkich tworzonych w ty
m zadaniu klasyfikatorów na zestawie danych 
Titanic. 

**Zadanie 3.** (2 punkty) <br/>
Zapoznaj  si
ę
  z  implementacj
ą
  algorytmów  Random  Forest  i  Extremely  Randomized  Tr
ees  w 
pakiecie SciKit (http://scikit-learn.org/stable/modules/ensemble.html#forest). U
ż
yj ich do klasyfikacji 
danych  IRIS  oraz  Titanic.  Oce
ń
  ich  skuteczno
ść
  dziel
ą
c  dane  na  dwa  zestawy  lub  robi
ą
c  cross 
validation. 

In [3]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import tree
import pandas as pd
from sklearn.metrics import confusion_matrix

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()

In [10]:
X = iris.data
y = iris.target

clf = DecisionTreeClassifier(max_depth=2, splitter='random', min_samples_split=2, random_state=2)
clf = clf.fit(X, y)
print (clf.score(X, y))
scores = cross_val_score(clf, X, y)
print('Cross-validation for random decision tree for IRIS: ', scores.mean())
#confusion_matrix(y, y_pred)

clf = RandomForestClassifier(n_estimators=4, max_depth=2, min_samples_split=2, random_state=2)
clf = clf.fit(X, y)
print (clf.score(X, y))
scores = cross_val_score(clf, X, y)
print('Cross-validation for Random Forest for IRIS: ', scores.mean()) 

clf = ExtraTreesClassifier(n_estimators=4, max_depth=2, min_samples_split=2, random_state=2)
clf = clf.fit(X, y)
print (clf.score(X, y))
scores = cross_val_score(clf, X, y)
print('Cross-validation for Extremely Randomized Trees for IRIS: ', scores.mean()) 

0.773333333333
('Cross-validation for random decision tree for IRIS: ', 0.74019607843137258)
0.96
('Cross-validation for Random Forest for IRIS: ', 0.95343137254901966)
0.94
('Cross-validation for Extremely Randomized Trees for IRIS: ', 0.93300653594771232)


In [187]:
data = pd.read_csv("train.csv")
data = data.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis = 1)
data = data.dropna()
data['Sex'] = pd.Categorical.from_array(data['Sex']).codes
data['Embarked'] = pd.Categorical.from_array(data['Embarked']).codes
data.head()

/pio/lscratch/1/os/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Categorical.from_array is deprecated, use Categorical instead
  after removing the cwd from sys.path.
/pio/lscratch/1/os/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Categorical.from_array is deprecated, use Categorical instead
  """


Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [188]:
y = data['Survived']
X = data.drop('Survived', axis = 1)

In [189]:
t = tree.DecisionTreeClassifier()
t = t.fit(X, y)
t.score(X, y)

0.9859550561797753

In [190]:
t = DecisionTreeClassifier(max_depth=6, splitter='random', min_samples_split=2, random_state=2)
t = t.fit(X, y)
print('Random decision tree for Titanic: ', t.score(X, y))
print('Cross-validation for random decision tree for Titanic: ', cross_val_score(t, X, y).mean())

t = RandomForestClassifier(n_estimators=10, max_depth=6, min_samples_split=2, random_state=2)
t = t.fit(X, y)
print('Random Forest for Titanic: ', t.score(X, y))
print('Cross-validation for Random Forest for Titanic: ', cross_val_score(t, X, y).mean())

t = ExtraTreesClassifier(n_estimators=10, max_depth=6, min_samples_split=2, random_state=2)
t = t.fit(X, y)
print('Extremely Randomized Trees for Titanic: ',t.score(X, y))
print('Cross-validation for Extremely Randomized Trees for Titanic: ', cross_val_score(t, X, y).mean())

('Random decision tree for Titanic: ', 0.851123595505618)
('Cross-validation for random decision tree for Titanic: ', 0.7893309222423146)
('Random Forest for Titanic: ', 0.8679775280898876)
('Cross-validation for Random Forest for Titanic: ', 0.78939001761041971)
('Extremely Randomized Trees for Titanic: ', 0.827247191011236)
('Cross-validation for Extremely Randomized Trees for Titanic: ', 0.78515878925409821)


**Zadanie 4.** (2 punkty) <br/>
Zbiór  danych  Mushroom  (http://archive.ics.uci.edu/ml/datasets/Mushroom)  zawiera  informacje  o 
grzybach i o tym czy s
ą
 one jadalne, truj
ą
ce, nie polecane do jedzenia lub nieznane. Zapoznaj
 si
ę
z tym zbiorem danych i stwórz drzewo decyzyjne okre
ś
laj
ą
ce jadalno
ść
 grzybów na podstawie ich 
cech okre
ś
lonych w zestawie danych. 

In [27]:
data = pd.read_csv("agaricus-lepiota.data")
for column in data.columns.values:
    data[column] = pd.Categorical.from_array(data[column]).codes
data.head()

/pio/lscratch/1/os/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Categorical.from_array is deprecated, use Categorical instead
  This is separate from the ipykernel package so we can avoid doing imports until


edible  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0       1          5            2          4        1     6                1   
1       0          5            2          9        1     0                1   
2       0          0            2          8        1     3                1   
3       1          5            3          8        1     6                1   
4       0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color   ...     stalk-surface-below-ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [28]:
y = data['edible']
X = data.drop('edible', axis = 1)

In [29]:
t = tree.DecisionTreeClassifier()
t = t.fit(X, y)
print('Decision tree for Mushrooms: ', t.score(X, y))
print('Cross-validation for Extremely Randomized Trees for Mushrooms: ', cross_val_score(t, X, y).mean())


('Decision tree for Mushrooms: ', 1.0)
('Cross-validation for Extremely Randomized Trees for Mushrooms: ', 0.87442843242099411)


In [30]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

In [32]:
y_pred = cross_val_predict(t,X,y,cv=10)
conf_mat = confusion_matrix(y,y_pred)
conf_mat

array([[4160,   48],
       [ 256, 3660]])

In [57]:
def visualize_tree(tree, feature_names):
    """Create tree png using graphviz.

    Args
    ----
    tree -- scikit-learn DecsisionTree.
    feature_names -- list of feature names.
    """
    with open("dt.dot", 'w') as f:
        export_graphviz(tree, out_file=f,
                        feature_names=feature_names)

    command = ["dot", "-Tpng", "dt.dot", "-o", "dt.png"]
    try:
        subprocess.check_call(command)
    except:
        exit("Could not run dot, ie graphviz, to "
             "produce visualization")
visualize_tree(t, data.columns.values[1:])

**Zadanie 5.** (2 punkty) <br/>
Zbiór   danych   Car   Evaluation   (http://archive.ics.uci.edu/ml/datasets/Car+Evaluation)   zawiera 
informacje o samochodach i rekomendacje dotycz
ą
c
ą
 ich ewentualnego kupna. Zapoznaj si
ę
 z tym 
zbiorem danych i stwórz dla niego drzewo decyzyjne.

In [193]:
data = pd.read_csv("car.data")
for column in data.columns.values:
    data[column] = pd.Categorical.from_array(data[column]).codes
data.head()

/pio/lscratch/1/os/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Categorical.from_array is deprecated, use Categorical instead
  This is separate from the ipykernel package so we can avoid doing imports until


buying  maint  doors  persons  lug_boot  safety  acceptability
0       3      3      0        0         2       1              2
1       3      3      0        0         2       2              2
2       3      3      0        0         2       0              2
3       3      3      0        0         1       1              2
4       3      3      0        0         1       2              2

In [194]:
y = data['acceptability']
X = data.drop('acceptability', axis = 1)

In [195]:
t = tree.DecisionTreeClassifier()
t = t.fit(X, y)
print('Decision tree for Cars: ', t.score(X, y))
print('Cross-validation for Extremely Randomized Trees for Cars: ', cross_val_score(t, X, y).mean())

('Decision tree for Cars: ', 1.0)
('Cross-validation for Extremely Randomized Trees for Cars: ', 0.78939060419963314)


In [196]:
y_pred = cross_val_predict(t,X,y,cv=10)
conf_mat = confusion_matrix(y,y_pred)
conf_mat

array([[ 269,   30,   74,   11],
       [   7,   55,    3,    4],
       [  91,    2, 1117,    0],
       [   6,    1,    0,   58]])

In [197]:
visualize_tree(t, data.columns.values[:-1])

In [200]:
t = tree.DecisionTreeClassifier(class_weight={0:2,1:10,2:1,3:10})
t = t.fit(X, y)
print('Decision tree for Cars: ', t.score(X, y))
print('Cross-validation for Extremely Randomized Trees for Cars: ', cross_val_score(t, X, y).mean())
y_pred = cross_val_predict(t,X,y,cv=10)
conf_mat = confusion_matrix(y,y_pred)
conf_mat

('Decision tree for Cars: ', 1.0)
('Cross-validation for Extremely Randomized Trees for Cars: ', 0.82183826576746277)


array([[ 297,   21,   53,   13],
       [  14,   51,    4,    0],
       [ 128,    3, 1079,    0],
       [   8,    0,    0,   57]])

**Zadanie 6.** (2 punkty) <br/>
Zbiór   danych   Bank   Marketing   (http://archive.ics.uci.edu/ml/datasets/Bank+Marketing)   zawiera 
informacje  o  klientach  banku  i  ich  zainteresowaniu 
lokatami  bankowymi.  Zapoznaj  si
ę
  z  tym 
zbiorem danych i na jego podstawie stwórz drzewo de
cyzyjne pozwalaj
ą
ce przewidywa
ć
 czy klient 
banku b
ę
dzie zainteresowany lokatami czy nie na podstawie z
gromadzonych o nim informacji. 

In [58]:
data = pd.read_csv("bank.csv", sep=';')
for column in data.columns.values:
    data[column] = pd.Categorical.from_array(data[column]).codes
data.head()

/pio/lscratch/1/os/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Categorical.from_array is deprecated, use Categorical instead
  This is separate from the ipykernel package so we can avoid doing imports until


age  job  marital  education  default  balance  housing  loan  contact  \
0   11   10        1          0        0     1475        0     0        0   
1   14    7        1          1        0     2030        1     1        0   
2   16    4        2          2        0     1303        1     0        0   
3   11    4        1          2        0     1352        1     1        2   
4   40    1        1          1        0      274        1     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  y  
0   18     10        75         0      0         0         3  0  
1   10      8       216         0    228         4         0  0  
2   15      0       181         0    219         1         0  0  
3    2      6       195         3      0         0         3  0  
4    4      8       222         0      0         0         3  0

In [59]:
y = data['y']
X = data.drop('y', axis = 1)

In [60]:
t = tree.DecisionTreeClassifier()
t = t.fit(X, y)
print('Decision tree for Deposits: ', t.score(X, y))
print('Cross-validation for Extremely Randomized Trees for Deposits: ', cross_val_score(t, X, y).mean())

('Decision tree for Deposits: ', 1.0)
('Cross-validation for Extremely Randomized Trees for Deposits: ', 0.86175796842844232)


In [61]:
y_pred = cross_val_predict(t,X,y,cv=10)
conf_mat = confusion_matrix(y,y_pred)
conf_mat

array([[3698,  302],
       [ 299,  222]])

In [62]:
visualize_tree(t, data.columns.values[:-1])

In [63]:
data = data.drop(['contact', 'day', 'month'], axis = 1)
data = data.dropna()
data.head()
y = data['y']
X = data.drop('y', axis = 1)

In [182]:
t = DecisionTreeClassifier(max_features='auto', class_weight={0:1,1:5})
t = t.fit(X, y)
print('Decision tree for Deposits: ', t.score(X, y))
print('Cross-validation for Extremely Randomized Trees for Deposits: ', cross_val_score(t, X, y).mean())
y_pred = cross_val_predict(t,X,y,cv=10)
conf_mat = confusion_matrix(y,y_pred)
conf_mat

('Decision tree for Deposits: ', 1.0)
('Cross-validation for Extremely Randomized Trees for Deposits: ', 0.85511639599391287)


array([[3698,  302],
       [ 336,  185]])

**Zadanie 7.** (2 punkty bonusowe)
Zapoznaj    si
ę
    ze    zbiorem    danych    Human    Activity    Recognition    Using
    Smartphones 
(http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones).  Spróbuj 
stworzy
ć
  klasyfikator,  który  b
ę
dzie  rozpoznawał  czynno
ść
  wykonywan
ą
  przez  człowieka  na 
podstawie odczytów sensorów okre
ś
lonych w zestawie danych. 